[package]
name = "component-playground-desktop"
version.workspace = true
edition.workspace = true

[[bin]]
name = "component-playground-desktop"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
component-playground-ui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
image.workspace = true

[target.'cfg(windows)'.build-dependencies]
embed-resource.workspace = true
image.workspace = true
